using System.ComponentModel.DataAnnotations;

namespace PharmacyManagementSystem.Web.Models
{
    public class Medicine
    {
        // ============================================================
        // SYSTEM ID
        // Automatically generated by MySQL AUTO_INCREMENT
        // ============================================================

        public int Id { get; set; }


        // ============================================================
        // COMPANY MEDICINE ID
        // ID / code printed by the pharmaceutical company
        // This is entered manually by the user.
        // ============================================================

        [Display(Name = "Company Medicine ID")]
        [StringLength(100)]
        public string? CompanyMedicineId { get; set; }


        // ============================================================
        // MEDICINE NAME
        // REQUIRED
        // ============================================================

        [Required(ErrorMessage = "Medicine name is required.")]
        [StringLength(
            100,
            ErrorMessage = "Medicine name cannot exceed 100 characters.")]
        public string Name { get; set; } = string.Empty;


        // ============================================================
        // CATEGORY
        // OPTIONAL
        // ============================================================

        [StringLength(
            100,
            ErrorMessage = "Category cannot exceed 100 characters.")]
        public string? Category { get; set; }


        // ============================================================
        // COMPANY
        // OPTIONAL
        // ============================================================

        [StringLength(
            150,
            ErrorMessage = "Company cannot exceed 150 characters.")]
        public string? Company { get; set; }


        // ============================================================
        // FORMULA
        // OPTIONAL
        // ============================================================

        [StringLength(
            200,
            ErrorMessage = "Formula cannot exceed 200 characters.")]
        public string? Formula { get; set; }


        // ============================================================
        // MG / STRENGTH
        // OPTIONAL
        // ============================================================

        [StringLength(
            50,
            ErrorMessage = "MG cannot exceed 50 characters.")]
        public string? Mg { get; set; }


        // ============================================================
        // PRICE
        // REQUIRED
        // ============================================================

        [Required(ErrorMessage = "Price is required.")]
        [Range(
            0.01,
            double.MaxValue,
            ErrorMessage = "Price must be greater than zero.")]
        public decimal Price { get; set; }


        // ============================================================
        // QUANTITY
        // REQUIRED
        // ============================================================

        [Required(ErrorMessage = "Quantity is required.")]
        [Range(
            0,
            int.MaxValue,
            ErrorMessage = "Quantity cannot be negative.")]
        public int Quantity { get; set; }


        // ============================================================
        // EXPIRY DATE
        // OPTIONAL
        // ============================================================

        [Display(Name = "Expiry Date")]
        public DateTime? ExpiryDate { get; set; }


        // ============================================================
        // CREATED DATE
        // ============================================================

        public DateTime CreatedAt { get; set; }


        // ============================================================
        // EDITED DATE
        // ============================================================

        public DateTime? EditedAt { get; set; }
    }
}